### ISSUE TITLE
Code uses mix of spaces and tabs indentation, which leads to the editor throwing up errors

### ISSUE THREAD

**Issue by 8bitprodigy** [NodotProject/nodot#76]
When installing the addon in a fresh godot project with default settings, the mix of tabs and spaces for indents leads to parse errors, making it impossible to run any of the examples or just use the addon at all. I have no idea why anyone would use spaces for indentations, and I've never seen any other project but this one using spaces for indentation.

To fix this, all code block indentations should be tabs instead of spaces.

**Comment by krazyjakee** [comment]
These issues should now be resolved on the main branch. I've also updated the download link on the asset store but it may take a couple of days for moderators to accept the change.
