### ISSUE TITLE
Can't run example: Could not find type Saver in the current scope

### ISSUE THREAD

**Issue by mathewcst** [NodotProject/nodot#86]
I've just cloned the repo and tried to run the FPS example. Immediately got the error:
```
Line 9:Could not find type "Saver" in the current scope.
Line 14:Could not find type "Saver" in the current scope.
Line 20:Could not find type "Saver" in the current scope.
```
All from SaveManager.gd

![image](https://user-images.githubusercontent.com/5620645/236336867-7e7420f9-56b8-44dc-8c16-8106cc02c043.png)

**Comment by krazyjakee** [comment]
Have you enabled the plugin?

**Comment by mathewcst** [comment]
@krazyjakee yes, I literally cloned the repo, opened in Godot 4.0.2 (stable) and tried to run the FPS->Map

The plugin is enable and the AutoLoads were added.

**Comment by krazyjakee** [comment]
https://github.com/NodotProject/nodot/blob/main/addons/nodot/utility/Saver.gd

Is this file in your local directory?

**Comment by mathewcst** [comment]
Yeah.

I've cloned the entire main branch just to run the examples.

I was using the **GodotSteam** 4.0.2 stable.


https://user-images.githubusercontent.com/5620645/236339893-d6dcc4a7-3855-4b29-9a12-3b8f23949fdb.mp4


After cloning again and using the **official** stable version, seems to work fine.

https://user-images.githubusercontent.com/5620645/236339987-066a7920-e1be-4aab-b829-0c63bee5db88.mp4

Idk what happened there hahahah

Thanks for the help =)

**Comment by krazyjakee** [comment]
This is good to know, thanks
